### ISSUE TITLE
Conversion aborted

### ISSUE THREAD

**Issue by Tobi73** [dmryutov/document2html#1]
I get this error during conversion of xlsx file:

`root@server:/storage/source/document2html-master/src# ./document2html -f ./data/7.xlsx -o ./testData
document2html: libs/fileext/excel/../../pugixml/pugixml.cpp:6718: pugi::xml_node& pugi::xml_named_node_iterator::operator*() const: Assertion `_wrap._root' failed.
Aborted`

Is there any way to handle this?
OS: Ubuntu 14.04
GCC: 5.4.1

**Comment by dmryutov** [comment]
Could you provide this file or more information about it?

**Comment by Tobi73** [comment]
File which causes the exception

[Таблица расчета Н(М)ЦК.xlsx](https://github.com/dmryutov/document2html/files/1711633/default.xlsx)

**Comment by dmryutov** [comment]
Please check this patch: 6f90b6404cd4833827059ad505dbe32140503f62

**Comment by Tobi73** [comment]
Thank you for paying attention to this problem, but conversion still crashes on the same file (with different error).

`root@file2:/storage/source/document2html/src# ./document2html -f ./data/Таблица\ расчета\ Н\(М\)ЦК.xlsx  -o test
document2html: libs/fileext/excel/../../pugixml/pugixml.cpp:6730: const pugi::xml_named_node_iterator& pugi::xml_named_node_iterator::operator++(): Assertion `_wrap._root' failed.
Aborted`

Sometimes conversion crashes with this error: 
`document2html: libs/fileext/excel/../../pugixml/pugixml.cpp:6718: pugi::xml_node& pugi::xml_named_node_iterator::operator*() const: Assertion `_wrap._root' failed.
Aborted`

But unfortunately I could not determine which file causes this.

**Comment by dmryutov** [comment]
Confirmed. My mistake - i shouldn't put variable `childrenCount` out of the loop. Please check 9c24aa05e9c80fd5a4379e00f9a67d8d336990c9. Your file was successfully converted on two my machines

**Comment by Tobi73** [comment]
Thank you very much for your help! Everything works now, I shall reopen this issue if we encounter this sort of exception again.
